### ISSUE TITLE
[Bug] Unable to switch account on Google Slides

### ISSUE THREAD

**Issue by jaeyongjaykim** [sidehustlelab/account-switcher#15]
Oddly, Account Switcher doesn't work on the following page:
https://docs.google.com/presentation/u/0/

**Comment by anshulahuja98** [comment]
Ack. Thanks for bringing this to notice.
We need to add this presentation regex in
https://github.com/anshulahuja98/account-switcher/blob/master/background.js

@jaeyongjaykim Let me know if you can help add this. It's mostly copying one entry and editing it as required.

**Comment by jaeyongjaykim** [comment]
Will do. @anshulahuja98
